import re

file_path = r'd:\RAJUAN-PERSONAL\VSCODE\victora\victory-fitness-app\app\(tabs)\challenge.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

mapping = {
    # Display / Heroes
    "brandTitle": "Fonts.display",
    "pageTitle": "Fonts.display",
    "challengeLibraryLead": "Fonts.display",
    "workoutShareTitle": "Fonts.display",
    "inviteModalTitle": "Fonts.display",
    "challengeInviteTitle": "Fonts.display",
    "confirmTitle": "Fonts.display",
    "chatAvatarEmoji": "Fonts.display",
    "feedAvatarText": "Fonts.display",
    "postAvatarText": "Fonts.display",
    "commentAvatarText": "Fonts.display",

    # Headings / Badges / Buttons / Labels
    "brandSubtitle": "Fonts.heading",
    "inviteBtnText": "Fonts.heading",
    "tabText": "Fonts.heading",
    "subSectionTitle": "Fonts.heading",
    "challengeLimitTitle": "Fonts.heading",
    "durationTabText": "Fonts.heading",
    "challengeLibraryCategory": "Fonts.heading",
    "challengeLibraryFieldLabel": "Fonts.heading",
    "challengeParticipantLabelText": "Fonts.heading",
    "verifiedAdminText": "Fonts.heading",
    "lockedBadgeText": "Fonts.heading",
    "lockedUpgradeBtnText": "Fonts.heading",
    "challengeExpandBtnText": "Fonts.heading",
    "challengeInviteBtnText": "Fonts.heading",
    "challengeStatusBtnText": "Fonts.heading",
    "chatName": "Fonts.heading",
    "activeCardTitle": "Fonts.heading",
    "completedTitle": "Fonts.heading",
    "readyTitle": "Fonts.heading",
    "difficultyText": "Fonts.heading",
    "startBtnText": "Fonts.heading",
    "communityInviteBtnText": "Fonts.heading",
    "feedUser": "Fonts.heading",
    "communityFilterOptionText": "Fonts.heading",
    "communityFilterDoneText": "Fonts.heading",
    "composerAttachmentBadgeText": "Fonts.heading",
    "composerAttachmentCloseText": "Fonts.heading",
    "composerMediaUploadOverlayText": "Fonts.heading",
    "composerMediaIndicatorText": "Fonts.heading",
    "postBtnText": "Fonts.heading",
    "workoutShareTrophyText": "Fonts.heading",
    "workoutShareCardOverlayText": "Fonts.heading",
    "workoutShareInputLabel": "Fonts.heading",
    "workoutSharePostBtnText": "Fonts.heading",
    "communityUploadOverlayText": "Fonts.heading",
    "communityPreviewRemoveText": "Fonts.heading",
    "postAuthor": "Fonts.heading",
    "tierBadgeText": "Fonts.heading",
    "postVideoBadgeText": "Fonts.heading",
    "postUploadingText": "Fonts.heading",
    "confirmCancelText": "Fonts.heading",
    "confirmDeleteText": "Fonts.heading",
    "fullscreenCardBadgeText": "Fonts.heading",
    "cardZoomHintText": "Fonts.heading",
    "commentAuthor": "Fonts.heading",
    "commentSendText": "Fonts.heading",
    "tierOptionTextActive": "Fonts.heading",
    "inviteChallengeBadgeTitle": "Fonts.heading",
    "inviteCopyBtnText": "Fonts.heading",
    "invitePrimaryShareBtnText": "Fonts.heading",
    "inviteSecondaryCommunityBtnText": "Fonts.heading",
    "workoutMilestoneBadgeText": "Fonts.heading",
    "challengeInvitePostBadgeText": "Fonts.heading",
    "challengeInviteCategoryChipText": "Fonts.heading",
    "challengeInviteAcceptBtnText": "Fonts.heading",
    "challengeInviteCopyBtnText": "Fonts.heading",

    # Data / Numbers / JetBrains Mono
    "challengeLimitCount": "Fonts.dataBold",
    "challengeParticipantCountText": "Fonts.dataBold",
    "challengeLibraryPointsText": "Fonts.dataBold",
    "challengeLibraryProgressText": "Fonts.dataBold",
    "unreadText": "Fonts.dataBold",
    "activePointsText": "Fonts.dataBold",
    "daysLeftText": "Fonts.dataBold",
    "completedPtsText": "Fonts.dataBold",
    "communityBannerCount": "Fonts.dataBold",
    "feedPtsText": "Fonts.dataBold",
    "communityFilterCountText": "Fonts.dataBold",
    "workoutShareRewardText": "Fonts.dataBold",
    "workoutSharePointsBadgeText": "Fonts.dataBold",
    "inviteChallengeDurationText": "Fonts.dataBold",
    "workoutPointsPillText": "Fonts.dataBold",
    "challengeInvitePointsPillText": "Fonts.dataBold",
    "challengeInviteStatChipText": "Fonts.dataBold",
    "chatTime": "Fonts.data",
    "feedTime": "Fonts.data",
    "postTime": "Fonts.data",
    "commentTime": "Fonts.data",
    "composerAttachmentSizeText": "Fonts.data",

    # Body / Explanations / Inputs
    "pageSubtitle": "Fonts.body",
    "challengeLimitText": "Fonts.body",
    "challengeStatusText": "Fonts.body",
    "challengeLoadingText": "Fonts.body",
    "challengeEmptyText": "Fonts.body",
    "lockedPostBlurredText": "Fonts.body",
    "lockedPromptText": "Fonts.bodyMedium",
    "challengeLibraryDescription": "Fonts.body",
    "challengeWhyText": "Fonts.body",
    "challengeLibraryMetaText": "Fonts.bodyMedium",
    "chatLastMsg": "Fonts.body",
    "progressLabel": "Fonts.body",
    "activeMetaText": "Fonts.body",
    "completedMeta": "Fonts.body",
    "readyDesc": "Fonts.body",
    "metaText": "Fonts.body",
    "upcomingNoticeText": "Fonts.body",
    "communityBannerLabel": "Fonts.body",
    "feedText": "Fonts.body",
    "searchInput": "Fonts.body",
    "composerInput": "Fonts.body",
    "composerLinkInput": "Fonts.body",
    "composerLinkHint": "Fonts.body",
    "composerLinkInputField": "Fonts.body",
    "tierText": "Fonts.body",
    "workoutShareInput": "Fonts.body",
    "communityErrorText": "Fonts.body",
    "communityLoadingText": "Fonts.body",
    "postBody": "Fonts.body",
    "postActionText": "Fonts.body",
    "confirmText": "Fonts.body",
    "postModalBody": "Fonts.body",
    "commentContent": "Fonts.body",
    "commentInput": "Fonts.body",
    "tierOptionText": "Fonts.body",
    "inviteModalSubtitle": "Fonts.body",
    "invitePerkText": "Fonts.body",
    "inviteLinkText": "Fonts.body",
    "workoutMilestoneText": "Fonts.bodyMedium",
    "challengeInviteSubtitle": "Fonts.body",
}

for style_name, font_val in mapping.items():
    pattern = rf'({style_name}:\s*\{{[^}}]*?fontFamily:\s*)([\'"][^\'"]+[\'"])'
    text = re.sub(pattern, rf'\g<1>{font_val}', text)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print(f"Applied {len(mapping)} typography rules to app/(tabs)/challenge.tsx!")
