import re

file_path = r'd:\RAJUAN-PERSONAL\VSCODE\victora\victory-fitness-app\app\(tabs)\profile.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

target_marker = 'const styles = StyleSheet.create({'
idx = content.find(target_marker)
if idx == -1:
    print("Could not find styles marker!")
    exit(1)

new_styles = """const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.obsidian },
  scroll: { paddingBottom: 36 },

  /* ── 1. Hero Passport Card ── */
  heroCard: {
    marginHorizontal: 16,
    borderRadius: 24,
    padding: 20,
    backgroundColor: Colors.surfaceCard,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.28)',
    marginBottom: 14,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  heroTopRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  tierPlanPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
  },
  tierPlanPillText: {
    color: Colors.gold,
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 0.5,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(26, 122, 74, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(26, 122, 74, 0.35)',
  },
  verifiedBadgeText: {
    color: Colors.victoryGreen,
    fontSize: 10,
    fontFamily: Fonts.heading,
    letterSpacing: 0.6,
  },
  avatarWrap: {
    position: 'relative',
    width: 86,
    height: 86,
    marginBottom: 14,
  },
  avatarImage: {
    width: 86,
    height: 86,
    borderRadius: 43,
    resizeMode: 'cover',
    borderWidth: 2,
    borderColor: 'rgba(181, 101, 29, 0.45)',
  },
  avatarFallback: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.navy,
    borderWidth: 2,
    borderColor: 'rgba(181, 101, 29, 0.45)',
  },
  avatarFallbackText: {
    color: Colors.gold,
    fontFamily: Fonts.display,
    fontSize: 26,
    letterSpacing: 1,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.surfaceCard,
  },
  identityBlock: {
    alignItems: 'center',
    marginBottom: 12,
    width: '100%',
  },
  heroNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroName: {
    fontSize: 22,
    color: Colors.ivory,
    fontFamily: Fonts.display,
    letterSpacing: 0.3,
  },
  heroEmail: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: Fonts.body,
    marginTop: 3,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  rankBadge: {
    backgroundColor: 'rgba(13, 43, 69, 0.45)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  rankBadgeText: {
    color: Colors.gold,
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 0.4,
  },
  ptsBadge: {
    backgroundColor: 'rgba(201, 148, 58, 0.12)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.3)',
  },
  ptsBadgeText: {
    color: Colors.gold,
    fontSize: 11,
    fontFamily: Fonts.dataBold,
    letterSpacing: 0.4,
  },
  streakBadge: {
    backgroundColor: 'rgba(181, 101, 29, 0.15)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  streakBadgeText: {
    color: Colors.copper,
    fontSize: 11,
    fontFamily: Fonts.dataBold,
    letterSpacing: 0.4,
  },
  rankProgressWrap: {
    width: '100%',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
  },
  rankProgressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  rankProgressLabelLeft: {
    fontSize: 10,
    color: Colors.gold,
    fontFamily: Fonts.heading,
    letterSpacing: 0.6,
  },
  rankProgressLabelRight: {
    fontSize: 10,
    color: Colors.textSecondary,
    fontFamily: Fonts.dataBold,
    letterSpacing: 0.4,
  },
  rankBarBg: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  rankBarFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: Colors.gold,
  },

  /* ── 2. Performance 3-Metric KPI Bento Strip ── */
  kpiRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    gap: 10,
    marginBottom: 16,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: Colors.surfaceCard,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.22)',
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  kpiIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  kpiValue: {
    fontSize: 18,
    color: Colors.ivory,
    fontFamily: Fonts.dataBold,
    marginBottom: 3,
  },
  kpiLabel: {
    fontSize: 9,
    color: Colors.textSecondary,
    fontFamily: Fonts.heading,
    letterSpacing: 0.8,
  },

  /* ── 5. Athlete Mindset & Habit Anchors ── */
  mindsetCard: {
    marginHorizontal: 16,
    backgroundColor: Colors.surfaceCard,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  mindsetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  mindsetHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
    marginRight: 10,
  },
  mindsetTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  mindsetIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(201, 148, 58, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  mindsetTitle: {
    color: Colors.ivory,
    fontSize: 13,
    fontFamily: Fonts.heading,
    letterSpacing: 0.5,
  },
  mindsetSubtitle: {
    color: Colors.textSecondary,
    fontSize: 10,
    fontFamily: Fonts.body,
  },
  mindsetEditAction: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(201, 148, 58, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  identityQuoteBox: {
    backgroundColor: 'rgba(13, 43, 69, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.28)',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    position: 'relative',
  },
  quoteIcon: {
    position: 'absolute',
    top: 8,
    left: 10,
    opacity: 0.3,
  },
  identityQuoteText: {
    color: Colors.ivory,
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 19,
    fontFamily: Fonts.display,
    paddingLeft: 18,
  },
  quotePill: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(201, 148, 58, 0.18)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: 6,
  },
  quotePillText: {
    color: Colors.gold,
    fontSize: 9,
    fontFamily: Fonts.heading,
    letterSpacing: 0.5,
  },
  anchorItemsWrap: {
    gap: 8,
    marginBottom: 14,
  },
  anchorItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  anchorIconBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  anchorCopy: {
    flex: 1,
  },
  anchorItemLabel: {
    color: Colors.textSecondary,
    fontSize: 9,
    fontFamily: Fonts.heading,
    letterSpacing: 0.5,
  },
  anchorItemValue: {
    color: Colors.ivory,
    fontSize: 12,
    fontFamily: Fonts.bodySemiBold,
    marginTop: 2,
  },
  emptyMindsetText: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: Fonts.body,
    lineHeight: 18,
    paddingVertical: 6,
  },
  consistencyTrendBox: {
    backgroundColor: 'rgba(13, 43, 69, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    borderRadius: 12,
    padding: 12,
    marginTop: 4,
  },
  consistencyTrendHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  consistencyTrendTitle: {
    color: Colors.textSecondary,
    fontSize: 10,
    fontFamily: Fonts.heading,
    letterSpacing: 0.6,
  },
  consistencyTrendScore: {
    color: Colors.gold,
    fontSize: 15,
    fontFamily: Fonts.dataBold,
  },
  consistencyBarsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 72,
    gap: 8,
  },
  consistencyWeekCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  consistencyBarTrack: {
    width: '100%',
    maxWidth: 42,
    height: 48,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  consistencyBarFill: {
    width: '100%',
    backgroundColor: Colors.gold,
    borderRadius: 7,
  },
  consistencyWeekLabel: {
    color: Colors.textSecondary,
    fontSize: 9,
    fontFamily: Fonts.data,
    marginTop: 6,
  },
  consistencyTrendNote: {
    color: Colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontFamily: Fonts.body,
    marginTop: 8,
  },
  mindsetActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  mindsetPrimaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.gold,
    borderRadius: 12,
    paddingVertical: 10,
  },
  mindsetPrimaryBtnText: {
    color: Colors.obsidian,
    fontSize: 12,
    fontFamily: Fonts.heading,
  },
  mindsetSecondaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.navy,
    borderRadius: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  mindsetSecondaryBtnText: {
    color: Colors.ivory,
    fontSize: 12,
    fontFamily: Fonts.heading,
  },

  /* ── 6. Coaching & Membership Section ── */
  coachSection: {
    marginHorizontal: 16,
    marginBottom: 16,
  },
  coachCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceCard,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    marginBottom: 10,
    gap: 12,
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  lockedCard: {
    opacity: 0.75,
  },
  membershipPlanCard: {
    borderColor: 'rgba(201, 148, 58, 0.35)',
    backgroundColor: Colors.surfaceCard,
  },
  coachIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  coachInfo: {
    flex: 1,
  },
  coachName: {
    fontSize: 14,
    color: Colors.ivory,
    fontFamily: Fonts.heading,
    letterSpacing: 0.4,
  },
  coachStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 3,
  },
  onlineDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Colors.victoryGreen,
  },
  coachStatus: {
    fontSize: 11,
    color: Colors.gold,
    fontFamily: Fonts.bodyMedium,
  },
  coachLockedStatus: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontFamily: Fonts.body,
    marginTop: 2,
  },
  coachActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.gold,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  coachActionText: {
    color: Colors.obsidian,
    fontSize: 12,
    fontFamily: Fonts.heading,
  },
  membershipTierSubtext: {
    fontSize: 11,
    color: Colors.gold,
    fontFamily: Fonts.bodyMedium,
    marginTop: 2,
  },
  managePlanBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(201, 148, 58, 0.12)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.35)',
  },
  managePlanBadgeText: {
    color: Colors.gold,
    fontSize: 12,
    fontFamily: Fonts.heading,
  },

  /* ── 7. Menu Sections ── */
  menuSection: {
    marginHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 11,
    color: Colors.primary,
    fontFamily: Fonts.heading,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  menuCard: {
    backgroundColor: Colors.surfaceCard,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    overflow: 'hidden',
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  lockedRow: {
    opacity: 0.72,
  },
  menuIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuLabel: {
    flex: 1,
    fontSize: 14,
    color: Colors.ivory,
    fontFamily: Fonts.bodyMedium,
  },
  menuRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  menuValue: {
    fontSize: 12,
    color: Colors.textSecondary,
    fontFamily: Fonts.data,
  },
  lockedIconBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(181, 101, 29, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    marginHorizontal: 16,
  },

  /* ── 8. Privacy & Community ── */
  privacyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  privacyTextContainer: {
    flex: 1,
    paddingRight: 8,
  },
  privacyTitle: {
    fontSize: 14,
    color: Colors.ivory,
    fontFamily: Fonts.heading,
  },
  privacySubLabel: {
    color: Colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
    lineHeight: 16,
    fontFamily: Fonts.body,
  },

  /* ── 9. Log Out & Footer ── */
  logoutBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 6,
    paddingVertical: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
  },
  logoutText: {
    color: '#EF4444',
    fontSize: 14,
    fontFamily: Fonts.heading,
  },
  versionText: {
    textAlign: 'center',
    color: Colors.textSecondary,
    fontSize: 11,
    fontFamily: Fonts.data,
    marginTop: 18,
    letterSpacing: 0.4,
  },

  /* ── Modals ── */
  metricsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(13, 13, 13, 0.85)',
    justifyContent: 'center',
    padding: 20,
  },
  metricsModalCard: {
    backgroundColor: Colors.obsidian,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
    overflow: 'hidden',
  },
  metricsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  metricsModalTitle: {
    color: Colors.ivory,
    fontSize: 15,
    fontFamily: Fonts.display,
    letterSpacing: 1,
  },
  metricsFormGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  metricsInputGroup: {
    width: '48%',
    marginBottom: 16,
  },
  metricsInputLabel: {
    color: Colors.textSecondary,
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  metricsInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceCard,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
  },
  metricsInput: {
    flex: 1,
    color: Colors.ivory,
    fontSize: 16,
    fontFamily: Fonts.dataBold,
    outlineStyle: 'none' as any,
  },
  metricsInputUnit: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontFamily: Fonts.body,
  },
  metricsActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metricsCancelBtn: {
    flex: 1,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    backgroundColor: Colors.navy,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  metricsCancelBtnText: {
    color: Colors.ivory,
    fontSize: 14,
    fontFamily: Fonts.heading,
  },
  metricsSaveBtn: {
    flex: 1,
    backgroundColor: Colors.gold,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  metricsSaveBtnText: {
    color: Colors.obsidian,
    fontSize: 14,
    fontFamily: Fonts.heading,
  },
  metricsSavingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(13, 13, 13, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  metricsSavingCard: {
    backgroundColor: Colors.obsidian,
    borderRadius: 18,
    paddingHorizontal: 28,
    paddingVertical: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
    gap: 12,
  },
  metricsSavingText: {
    color: Colors.ivory,
    fontSize: 14,
    fontFamily: Fonts.heading,
  },
  habitKeyboardWrap: {
    width: '100%',
    justifyContent: 'center',
  },
  habitModalCard: {
    maxHeight: '82%',
  },
  habitModalScroll: {
    flexGrow: 0,
  },
  habitModalScrollContent: {
    paddingBottom: 8,
  },
  habitFieldLabel: {
    color: Colors.textSecondary,
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 0.8,
    marginBottom: 8,
    marginTop: 6,
  },
  habitInput: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    backgroundColor: Colors.surfaceCard,
    color: Colors.ivory,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: Fonts.body,
    marginBottom: 10,
    textAlignVertical: 'top',
    outlineStyle: 'none' as any,
  },
  genderModalCard: {
    backgroundColor: Colors.obsidian,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.35)',
  },
  genderModalTitle: {
    color: Colors.textSecondary,
    fontSize: 11,
    fontFamily: Fonts.display,
    letterSpacing: 1.2,
    textAlign: 'center',
    marginBottom: 18,
  },
  genderModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  genderModalOptionText: {
    color: Colors.textSecondary,
    fontSize: 15,
    fontFamily: Fonts.heading,
  },
  genderModalOptionTextActive: {
    color: Colors.gold,
  },
  profileLanguageList: {
    maxHeight: 360,
    width: '100%',
  },
  profileLanguageListContent: {
    gap: 10,
    paddingBottom: 2,
  },
  profileLanguageOption: {
    minHeight: 56,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    backgroundColor: Colors.surfaceCard,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileLanguageOptionActive: {
    borderColor: Colors.gold,
    backgroundColor: 'rgba(201, 148, 58, 0.15)',
  },
  profileLanguageOptionText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontFamily: Fonts.dataBold,
    letterSpacing: 0.8,
    width: 38,
  },
  profileLanguageOptionTextActive: {
    color: Colors.gold,
  },
  profileLanguageOptionCopy: {
    flex: 1,
  },
  profileLanguageNativeText: {
    color: Colors.ivory,
    fontSize: 15,
    fontFamily: Fonts.heading,
  },
  profileLanguageEnglishText: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontFamily: Fonts.body,
    marginTop: 2,
  },
});
"""

updated_content = content[:idx] + new_styles
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(updated_content)

print("Updated profile.tsx styles successfully!")
