import re

filepath = r"d:\RAJUAN-PERSONAL\VSCODE\victora\victory-fitness-app\app\challenges\progress\[challengeId].tsx"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Let's replace the whole style definition from `dayList: { gap: 12 },` to the end of styles!
target_styles_start = "  dayList: { gap: 12 },"

new_styles_block = """  dayList: { gap: 14 },
  dayCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(13, 43, 69, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    padding: 16,
    gap: 12,
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  dayCardCurrent: {
    borderColor: Colors.gold,
    shadowColor: Colors.gold,
    shadowOpacity: 0.15,
  },
  dayCardCompleted: {
    backgroundColor: 'rgba(26, 122, 74, 0.08)',
    borderColor: 'rgba(26, 122, 74, 0.45)',
  },
  dayCardMissed: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  dayNumberBadgeMissed: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  dayNumberTextMissed: {
    color: '#EF4444',
  },
  dayMissedLabel: {
    color: '#EF4444',
    fontSize: 11,
    fontFamily: Fonts.heading,
    marginTop: 4,
  },
  dayRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  dayLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  dayNumberBadge: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(247, 243, 238, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayNumberBadgeCurrent: {
    backgroundColor: Colors.gold,
    borderColor: Colors.gold,
  },
  dayNumberBadgeCompleted: {
    backgroundColor: Colors.victoryGreen,
    borderColor: Colors.victoryGreen,
  },
  dayNumberText: { color: Colors.ivory, fontSize: 13, fontFamily: Fonts.dataBold },
  dayNumberTextCurrent: { color: Colors.obsidian, fontFamily: Fonts.heading },
  dayNumberTextCompleted: { color: '#FFFFFF', fontFamily: Fonts.heading },
  dayTextWrap: { flex: 1 },
  dayTitle: { color: Colors.ivory, fontSize: 15, fontFamily: Fonts.display },
  dayFocus: { color: 'rgba(247, 243, 238, 0.65)', fontSize: 12, lineHeight: 18, fontFamily: Fonts.body, marginTop: 2 },
  dayRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dayPointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(201, 148, 58, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  dayPointsText: { color: Colors.gold, fontSize: 11, fontFamily: Fonts.dataBold },
  dayProgressBarBg: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(247, 243, 238, 0.08)',
    overflow: 'hidden',
    marginTop: 2,
  },
  dayProgressBarFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: Colors.gold,
  },
  dayProgressBarFillCompleted: {
    backgroundColor: Colors.victoryGreen,
  },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(13, 13, 13, 0.55)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.15)',
    marginTop: 4,
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
  },
  statLabel: {
    color: Colors.copper,
    fontSize: 9,
    fontFamily: Fonts.heading,
    letterSpacing: 1,
    marginBottom: 4,
  },
  statValue: {
    color: Colors.ivory,
    fontSize: 13,
    fontFamily: Fonts.dataBold,
  },
  statDivider: {
    width: 1,
    height: 22,
    backgroundColor: 'rgba(181, 101, 29, 0.2)',
  },
  dayMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  dayMetaText: { color: Colors.textMuted, fontSize: 11, fontFamily: Fonts.body },
  dayCurrentLabel: { color: Colors.gold, fontSize: 11, fontFamily: Fonts.heading },
  urgencyPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(201, 148, 58, 0.12)',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.28)',
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  urgencyPillText: {
    color: Colors.gold,
    fontSize: 11,
    fontFamily: Fonts.heading,
  },
  dayDetails: { gap: 12, marginTop: 8 },
  dayNotesCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(13, 43, 69, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.2)',
    borderRadius: 12,
    padding: 12,
  },
  dayNotesText: {
    color: 'rgba(247, 243, 238, 0.8)',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Fonts.body,
    flex: 1,
  },
  dayNotes: { color: Colors.textSecondary, fontSize: 12, lineHeight: 18, fontFamily: Fonts.body },
  helperText: { color: Colors.textMuted, fontSize: 12, lineHeight: 18, fontFamily: Fonts.bodyMedium },
  sectionHeader: {
    color: 'rgba(247, 243, 238, 0.55)',
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 1.5,
    marginTop: 6,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  sectionCard: {
    backgroundColor: 'rgba(13, 43, 69, 0.35)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.2)',
    padding: 14,
  },
  sectionCardCompleted: {
    borderColor: 'rgba(26, 122, 74, 0.4)',
    backgroundColor: 'rgba(26, 122, 74, 0.05)',
  },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  sectionLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  sectionStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(247, 243, 238, 0.18)',
  },
  sectionStatusDotCompleted: { backgroundColor: Colors.victoryGreen },
  sectionTitleWrap: { flex: 1 },
  sectionTitle: { color: Colors.ivory, fontSize: 14, fontFamily: Fonts.display },
  sectionDescription: { color: 'rgba(247, 243, 238, 0.65)', fontSize: 11, lineHeight: 16, fontFamily: Fonts.body, marginTop: 2 },
  sectionRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sectionActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionPointsBadge: {
    borderRadius: 999,
    backgroundColor: 'rgba(201, 148, 58, 0.12)',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.25)',
  },
  sectionPointsText: { color: Colors.gold, fontSize: 10, fontFamily: Fonts.dataBold },
  sectionMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  sectionMetaText: { color: 'rgba(247, 243, 238, 0.65)', fontSize: 11, fontFamily: Fonts.data, marginTop: 3 },
  sectionExercises: { gap: 8, marginTop: 10 },
  exerciseType: {
    color: Colors.copper,
    fontSize: 9,
    fontFamily: Fonts.heading,
    letterSpacing: 1,
    marginBottom: 2,
  },
  exerciseSubCardTitle: {
    color: Colors.ivory,
    fontSize: 14,
    fontFamily: Fonts.heading,
  },
  exerciseCheckButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(201, 148, 58, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.25)',
  },
  exerciseCheckButtonCompleted: {
    backgroundColor: Colors.victoryGreen,
    borderColor: Colors.victoryGreen,
  },
  exerciseSubCard: {
    backgroundColor: 'rgba(13, 13, 13, 0.65)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.18)',
  },
  exerciseSubCardCompleted: {
    borderColor: 'rgba(26, 122, 74, 0.35)',
    backgroundColor: 'rgba(26, 122, 74, 0.08)',
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  exerciseMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(201, 148, 58, 0.08)',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.2)',
  },
  metricItemVideo: {
    backgroundColor: 'rgba(201, 148, 58, 0.15)',
    borderColor: 'rgba(201, 148, 58, 0.35)',
  },
  metricValue: {
    color: Colors.ivory,
    fontSize: 12,
    fontFamily: Fonts.data,
  },
  exerciseNotes: {
    color: 'rgba(247, 243, 238, 0.55)',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Fonts.body,
    marginTop: 6,
  },
  completeSessionBtn: {
    backgroundColor: Colors.gold,
    borderRadius: 14,
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 2,
  },
  completeSessionBtnCompleted: {
    backgroundColor: Colors.victoryGreen,
  },
  completeSessionBtnText: {
    color: Colors.obsidian,
    fontSize: 13,
    fontFamily: Fonts.heading,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  completeSessionBtnTextCompleted: {
    color: '#FFFFFF',
  },
  compactButton: {
    borderRadius: 999,
    backgroundColor: Colors.gold,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  compactButtonCompleted: {
    backgroundColor: 'rgba(26, 122, 74, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(26, 122, 74, 0.4)',
  },
  compactButtonText: { color: Colors.obsidian, fontSize: 11, fontFamily: Fonts.heading },
  compactButtonTextCompleted: { color: Colors.ivory },
  readOnlyBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(247, 243, 238, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.2)',
  },
  readOnlyBadgeLarge: {
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  readOnlyBadgeText: {
    color: Colors.copper,
    fontSize: 11,
    fontFamily: Fonts.heading,
  },
  exerciseList: { gap: 8, marginTop: 4 },
  exerciseCard: {
    borderRadius: 12,
    backgroundColor: 'rgba(13, 13, 13, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.18)',
    padding: 10,
  },
  exerciseCardCompleted: {
    backgroundColor: 'rgba(26, 122, 74, 0.08)',
    borderColor: 'rgba(26, 122, 74, 0.35)',
  },
  exerciseActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  exerciseCheck: {
    minWidth: 34,
    minHeight: 40,
    paddingHorizontal: 10,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(201, 148, 58, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.25)',
  },
  exerciseCheckCompleted: {
    backgroundColor: Colors.victoryGreen,
    borderColor: Colors.victoryGreen,
  },
  exerciseCheckWide: {
    minWidth: 150,
    paddingHorizontal: 14,
  },
  exerciseCheckContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  exerciseCheckText: {
    color: Colors.gold,
    fontSize: 11,
    fontFamily: Fonts.heading,
  },
  exerciseCheckTextCompleted: {
    color: '#FFFFFF',
  },
  exerciseTextWrap: { flex: 1 },
  exerciseTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  exerciseName: { color: Colors.ivory, fontSize: 13, fontFamily: Fonts.heading, flex: 1 },
  exercisePoints: { color: Colors.gold, fontSize: 11, fontFamily: Fonts.dataBold },
  exerciseDetails: { color: Colors.textSecondary, fontSize: 12, lineHeight: 17, fontFamily: Fonts.body, marginTop: 3 },
  videoButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    backgroundColor: Colors.gold,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  videoButtonText: { color: Colors.obsidian, fontSize: 11, fontFamily: Fonts.heading },
  dayDoneButton: {
    marginTop: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(201, 148, 58, 0.3)',
    backgroundColor: 'rgba(201, 148, 58, 0.1)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  dayDoneButtonCompleted: {
    backgroundColor: Colors.victoryGreen,
    borderColor: Colors.victoryGreen,
  },
  dayDoneButtonText: { color: Colors.gold, fontSize: 12, fontFamily: Fonts.heading },
  dayDoneButtonTextCompleted: { color: '#FFFFFF' },
  readOnlyNoticeInline: {
    marginTop: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(13, 43, 69, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  readOnlyNoticeInlineText: {
    color: Colors.copper,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Fonts.bodyMedium,
  },
  completedDayActions: { flexDirection: 'row', gap: 10, marginTop: 10 },
  celebrationBackdrop: { flex: 1, backgroundColor: Colors.obsidian, alignItems: 'center', justifyContent: 'center', padding: 20, overflow: 'hidden' },
  confettiPiece: { position: 'absolute', top: -20, width: 8, height: 16, borderRadius: 2 },
  celebrationCard: { width: '100%', maxWidth: 390, backgroundColor: Colors.obsidian, borderRadius: 24, borderWidth: 1, borderColor: 'rgba(181, 101, 29, 0.35)', padding: 20, alignItems: 'center' },
  celebrationBadge: { width: 58, height: 58, borderRadius: 29, backgroundColor: Colors.gold, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  celebrationEyebrow: { color: Colors.copper, fontSize: 11, letterSpacing: 1.3, fontFamily: Fonts.heading },
  celebrationTitle: { color: Colors.ivory, fontSize: 24, textAlign: 'center', fontFamily: Fonts.display, marginTop: 6 },
  celebrationText: { color: Colors.textSecondary, fontSize: 13, lineHeight: 19, textAlign: 'center', fontFamily: Fonts.body, marginTop: 8 },
  celebrationPostcard: { width: '100%', alignItems: 'center' },
  postcardDots: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignContent: 'space-between', opacity: 0.15 },
  postcardDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: Colors.gold },
  
  /* Backdrop Styles */
  backdropDots: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
    opacity: 0.12,
  },
  backdropDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: Colors.gold,
    margin: 14,
  },
  celebrationCardContainer: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
  },
  floatingHeaderActions: {
    position: 'absolute',
    top: 24,
    right: 20,
    flexDirection: 'row',
    gap: 10,
    zIndex: 999,
  },
  floatingActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(13, 43, 69, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarOutlineBox: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.3)',
    backgroundColor: Colors.obsidian,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  avatarInnerBox: {
    width: 28,
    height: 28,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarQuestionMark: {
    color: Colors.obsidian,
    fontSize: 18,
    fontFamily: Fonts.heading,
  },
  
  /* New Postcard Redesign Styles */
  newPostcardLogoContainer: {
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  newPostcardBrandText: {
    color: Colors.ivory,
    fontSize: 28,
    fontFamily: Fonts.display,
    letterSpacing: -0.5,
    textAlign: 'center',
    marginTop: 4,
  },
  newPostcardCard: {
    backgroundColor: Colors.obsidian,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.3)',
    paddingHorizontal: 20,
    paddingVertical: 22,
    marginBottom: 14,
    width: '100%',
  },
  newPostcardLabel: {
    color: Colors.copper,
    fontSize: 10,
    letterSpacing: 1.5,
    fontFamily: Fonts.heading,
    marginBottom: 12,
    textAlign: 'center',
  },
  newPostcardTitle: {
    color: Colors.ivory,
    fontSize: 20,
    lineHeight: 26,
    fontFamily: Fonts.display,
    textAlign: 'center',
    marginBottom: 12,
  },
  newPostcardDivider: {
    height: 1,
    backgroundColor: 'rgba(181, 101, 29, 0.2)',
    marginBottom: 16,
    width: '100%',
  },
  newPostcardExercises: {
    gap: 10,
    width: '100%',
    paddingLeft: 8,
  },
  newPostcardExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  newPostcardBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.gold,
  },
  newPostcardExerciseText: {
    flex: 1,
    color: Colors.ivory,
    fontSize: 11,
    fontFamily: Fonts.heading,
    letterSpacing: 0.25,
  },
  newPostcardMetricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
    width: '100%',
    alignItems: 'stretch',
  },
  newPostcardMetricTile: {
    flex: 1,
    minWidth: 0,
    minHeight: 88,
    backgroundColor: 'rgba(13, 43, 69, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.25)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newPostcardMetricLabel: {
    color: Colors.copper,
    fontSize: 9,
    letterSpacing: 1.2,
    fontFamily: Fonts.heading,
    marginBottom: 6,
    textAlign: 'center',
  },
  newPostcardMetricValue: {
    color: Colors.ivory,
    fontSize: 20,
    lineHeight: 24,
    fontFamily: Fonts.dataBold,
    textAlign: 'center',
  },
  newPostcardMetricValueGut: {
    color: Colors.gold,
    fontSize: 18,
    lineHeight: 20,
    fontFamily: Fonts.dataBold,
    textAlign: 'center',
    width: '100%',
  },
  newPostcardUserPill: {
    backgroundColor: Colors.gold,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 24,
    maxWidth: '82%',
    alignSelf: 'center',
    marginBottom: 14,
  },
  newPostcardUserPillText: {
    color: Colors.obsidian,
    fontSize: 12,
    fontFamily: Fonts.heading,
    letterSpacing: 1.1,
    textAlign: 'center',
  },
  newPostcardUrl: {
    color: 'rgba(247, 243, 238, 0.4)',
    textAlign: 'center',
    fontSize: 9,
    letterSpacing: 2.2,
    fontFamily: Fonts.heading,
    marginTop: 8,
  },
  shareCommunityBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.gold,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
    marginTop: 16,
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  shareCommunityBtnText: {
    color: Colors.obsidian,
    fontFamily: Fonts.heading,
    fontSize: 13,
    letterSpacing: 0.6,
  },

  postcardShareLabel: { color: Colors.ivory, fontSize: 10, letterSpacing: 1.2, fontFamily: Fonts.heading, marginTop: 12 },
  postcardSocialRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', width: '100%', marginTop: 8, paddingHorizontal: 4 },
  celebrationPrimary: { width: '100%', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: Colors.gold, borderRadius: 12, paddingVertical: 13, marginTop: 16 },
  celebrationPrimaryText: { color: Colors.obsidian, fontSize: 13, fontFamily: Fonts.heading },
  celebrationSecondary: { width: '100%', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: 'rgba(181, 101, 29, 0.35)', borderRadius: 12, paddingVertical: 12, marginTop: 9 },
  celebrationSecondaryText: { color: Colors.gold, fontSize: 13, fontFamily: Fonts.heading },
  cardActions: { width: '100%', flexDirection: 'row', gap: 10, marginTop: 12 },
  cardActionButton: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(181, 101, 29, 0.3)',
    borderRadius: 12,
    backgroundColor: 'rgba(201, 148, 58, 0.08)',
  },
  cardActionButtonBusy: { opacity: 0.5 },
  cardActionText: { color: Colors.gold, fontSize: 13, fontFamily: Fonts.heading },
  celebrationClose: { paddingVertical: 10, marginTop: 3 },
  celebrationCloseText: { color: Colors.textMuted, fontSize: 12, fontFamily: Fonts.heading },
  buttonDisabled: { opacity: 0.5 },
});"""

idx = content.find(target_styles_start)
if idx != -1:
    content = content[:idx] + new_styles_block + "\n"
    print("Successfully replaced styles!")
else:
    print("Could not find target_styles_start!")

# Also clean up top card styles:
content = content.replace("backgroundColor: '#101827',", "backgroundColor: Colors.obsidian,")
content = content.replace("backgroundColor: '#0D1526',", "backgroundColor: 'rgba(13, 43, 69, 0.45)',")
content = content.replace("backgroundColor: 'rgba(0,240,208,0.1)',", "backgroundColor: 'rgba(201, 148, 58, 0.12)',")
content = content.replace("borderColor: 'rgba(0,240,208,0.16)',", "borderColor: 'rgba(181, 101, 29, 0.25)',")
content = content.replace("borderColor: 'rgba(245,158,11,0.16)',", "borderColor: 'rgba(201, 148, 58, 0.25)',")
content = content.replace("borderColor: 'rgba(245,158,11,0.2)',", "borderColor: 'rgba(181, 101, 29, 0.25)',")
content = content.replace("color: '#FCD34D',", "color: Colors.gold,")
content = content.replace("backgroundColor: 'rgba(245,158,11,0.08)',", "backgroundColor: 'rgba(201, 148, 58, 0.08)',")
content = content.replace("backgroundColor: 'rgba(245,158,11,0.12)',", "backgroundColor: 'rgba(201, 148, 58, 0.12)',")
content = content.replace("color: '#F59E0B',", "color: Colors.gold,")

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated progress styles successfully!")
